//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org
    {
        public System.Guid Id { get; set; }
        public string CascadeId { get; set; }
        public string Name { get; set; }
        public string HotKey { get; set; }
        public string ParentName { get; set; }
        public bool IsLeaf { get; set; }
        public bool IsAutoExpand { get; set; }
        public string IconName { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public string BizCode { get; set; }
        public string CustomCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateId { get; set; }
        public int SortNo { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
    }
}
