//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_FrmMain
    {
        public System.Guid Id { get; set; }
        public string FrmCode { get; set; }
        public string FrmName { get; set; }
        public string FrmType { get; set; }
        public string FrmDbId { get; set; }
        public string FrmTable { get; set; }
        public Nullable<int> isSystemTable { get; set; }
        public string FrmTableId { get; set; }
        public string FrmContent { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
